### ISSUE TITLE
Elixir of Minor Accuracy missing

### ISSUE THREAD

**Issue by AKASecret** [DFortun81/ATT-WRATH-Classic#9] opened 2022-09-14 21:06 UTC
ATT-Classic Missing Elixir of Minor Accuracy spellID in ATT Database. Please report it!
![ElixirMissing](https://user-images.githubusercontent.com/35233062/190262408-f6140132-cd11-4b5f-8367-e6a120d6127e.png)

**Comment by Molkree** [comment] 2022-09-18 17:31
Duplicate of #4

**Closed by Molkree** 2022-09-18 17:31 UTC
